config_file: .env.example
repository: duc/sso
chart: xuanji/sso-chart
helm_repo_name: xuanji 
helm_repo_url: http://localhost:8080 
default_values:
  - 'redis.enabled=true'
  - 'redis.cluster.slaveCount=0'
  - 'redis.usePassword=false'
  - 'service.type=NodePort'
tag_format: "$branch-$commit"
branches:
  - master
extra: |
  daadas: daadas
  da: 12